### ISSUE TITLE
VGGVox does not install with vl_contrib

### ISSUE THREAD

**Issue by xwasco** [vlfeat/matconvnet-contrib#1] opened 2017-12-18 12:42 UTC
Hi all, we have the following issue installing the VGGVox:

vl_contrib install VGGVox

Error using vl_contrib>repo_factory (line 375)
Invalid repository https://github.com/a-nagrani/VGGVox.

Error in vl_contrib>module_init (line 136)
module.repo = repo_factory(module.url);

Error in vl_contrib (line 97)
  module = module_init(contribs(module_id), opts);

same thing happens when we list all the repos.

Could you please tell me how to solve it ? maybe the problem is related to the name of the repo.

Thanks

**Comment by jotaf98** [comment] 2017-12-23 14:26
Thanks for noticing that; I pushed a fix to MatConvNet's vl_contrib function that should correct this. It's in the master branch of https://github.com/vlfeat/matconvnet

**Closed as completed by jotaf98** 2017-12-23 14:26 UTC

**Comment by hktxt** [comment] 2018-10-22 10:22
> Hi all, we have the following issue installing the VGGVox:
> 
> vl_contrib install VGGVox
> 
> Error using vl_contrib>repo_factory (line 375)
> Invalid repository https://github.com/a-nagrani/VGGVox.
> 
> Error in vl_contrib>module_init (line 136)
> module.repo = repo_factory(module.url);
> 
> Error in vl_contrib (line 97)
> module = module_init(contribs(module_id), opts);
> 
> same thing happens when we list all the repos.
> 
> Could you please tell me how to solve it ? maybe the problem is related to the name of the repo.
> 
> Thanks

same problem, solve it?

**Comment by jotaf98** [comment] 2018-10-26 10:28
This seems like it was caused by some update to GitHub's handling of HTTPS (certificates maybe?) that Matlab (or actually the underlying Java libraries) doesn't handle.

I'm looking into it, but in the meanwhile just download and extract [VGGVox](https://github.com/a-nagrani/VGGVox) to `<matconvnet-directory>/contrib`. If you prefer git, you can also clone the repo there.

**Comment by SwapnilBorse123** [comment] 2018-11-14 04:43
@jotaf98 I tried to install VGGVox recently and I am getting the same error. I read your most recent comment about cloning VGGVox to <matconvnet-dir>/contrib directory. After cloning it there can you guide me with the next steps on actually having it installed? or simply copying is as good as installed?

Sorry if the question is naive. I am a newbie in matlab. Thanks a ton in advance for your support and understanding.

**Comment by jotaf98** [comment] 2018-11-14 16:00
Yes, copying is all you need to install it.

You can then set up the paths in Matlab with `vl_contrib setup VGGVox`, or manually -- just run the "setup_VGGVox.m" file that comes with the code.

**Comment by SwapnilBorse123** [comment] 2018-11-14 21:43
@jotaf98 thanks a lot for such a prompt and quick reply. I could make some progress due to your guidance. I am having a different error now. I don't have a GPU on my machine. So I am wanting to use the non gpu option. So what changes would you suggest in the `demo_vggvox_identif.m` file?
I tried changing `opts.gpu=3` to `opts.gpu=0` but I am getting the below stack trace

There is a problem with the graphics driver or with this GPU device. Be sure that you have a supported
GPU and that the latest driver is installed.

Error in test_getinput (line 19)
	inp(:,:) = gpuArray(single(nSPEC(:,rstart:rstart+rsize-1)));

Error in demo_vggvox_identif (line 47)
inp = test_getinput(inpPath,net.meta,buckets);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Caused by:
    The graphics driver was found, but it is too old. The graphics driver on your system supports CUDA
    version 9. The required CUDA version is 9.1 or greater.

I also tried doing `opts.gpu = []` to try to make it empty thinking that it would skip the `if ~isempty(opts.gpu),net = vl_simplenn_move(net,'gpu'); end` condition.

I am trying hard to make it run using only a CPU for my project. Kindly suggest me changes to make it run `using only a cpu`. Your earlier suggestion of setting up VGGVox from the file directly with a copy paste has worked nice and smooth. Thanks a lot in advance for more help!
